# Azure Pipelines CI

trigger:
  branches:
    include:
      - develop
      - master
  tags:
    include:
      - '*.*.*'
pr:
  - develop
  - master

variables:
  BuildConfiguration: Debug
  VersionSuffix: CI-$(Build.BuildNumber)

pool:
  vmImage: ubuntu-20.04

steps:

- task: Bash@3
  condition: startsWith(variables['Build.SourceBranch'], 'ref/tags/')
  displayName: Set up Release build
  inputs:
    targetType: 'inline'
    script: |
      echo "##vso[task.setvariable variable=BuildConfiguration]Release"
      echo "##vso[task.setvariable variable=VersionSuffix]"

- task: UseDotNet@2
  displayName: Use SDK
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages
  inputs:
    command: 'restore'
    arguments: -c $(BuildConfiguration)

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    arguments: -c $(BuildConfiguration) --no-restore

- task: DotNetCoreCLI@2
  displayName: Run tests
  inputs:
    command: 'test'
    publishTestResults: true
    arguments: -c $(BuildConfiguration) --no-build

- task: DotNetCoreCLI@2
  displayName: Restore coverage reporting tool
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: restore

- task: DotNetCoreCLI@2
  displayName: Generate coverage report
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: >-
      run reportgenerator -reports:test/**/coverage.cobertura.xml
      -targetdir:Coverage -reporttypes:Cobertura

- task: PublishCodeCoverageResults@1
  displayName: Publish coverage report
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'Coverage/Cobertura.xml'

- task: DotNetCoreCLI@2
  displayName: Create NuGet package
  condition: eq(variables['Build.Reason'], 'IndividualCI')
  inputs:
    command: 'custom'
    projects: 'src/**/*.csproj'
    custom: 'pack'
    arguments: >-
      -c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)
      -p:VersionSuffix=$(VersionSuffix) --no-build

- task: NuGetCommand@2
  displayName: Publish NuGet package
  condition: eq(variables['Build.Reason'], 'IndividualCI')
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'MyGet'
